name: Jira Release on Tag

on:
  workflow_run:
    workflows: ["Auto Tag and Release on Merge"]
    types:
      - completed

jobs:
  jira_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables from workflow_run
        run: |
          echo "NEW_TAG=${{ github.event.workflow_run.outputs.TAG_NAME }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.workflow_run.outputs.PR_TITLE }}" >> $GITHUB_ENV

          echo "NEW_TAG: ${{ github.event.workflow_run.outputs.TAG_NAME }}"
          echo "PR_TITLE: ${{ github.event.workflow_run.outputs.PR_TITLE }}"

      - name: debug run
        env:
          TAG_NAME: ${{ env.NEW_TAG }}
          PR_TITLE: ${{ env.PR_TITLE }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          echo "$TAG_NAME $PR_TITLE $JIRA_URL"
